sudo: required
language: node_js
node_js:
  - "node"
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"  
  - docker pull selenium/standalone-chrome
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.11.0-antimony
  - yarn global add selenium-side-runner
script:
  - yarn lint
  - yarn test
  - yarn build:prod
deploy:
  provider: script
  skip_cleanup: true
  script: yarn release
  on:
    branch: master
